[env]
# used as directory of crate and program name
BOOTLOADER_NAME = "bootloader"
KERNEL_NAME = "kernel"
KERNEL_BUILD_TARGET_NAME = "x86_64-kernel"
BUILD = "build"

MOUNT_POINT_NAME = "mnt"
DISK_IMAGE_NAME = "boot.img"
OVMF_FILE_NAME = "OVMF-pure-efi.fd"

[tasks.ignore-members]
workspace = false

[tasks.build]
disabled = true

#
# create image
#
[tasks.make_image]
description = "Make a disk image"
script = [
    "qemu-img create -f raw ${BUILD}/${DISK_IMAGE_NAME} 200M",
    "mkfs.fat -n 'MAIZONO' -s 2 -f 2 -R 32 -F 32 ${BUILD}/${DISK_IMAGE_NAME}",
    "mkdir -p ${BUILD}/${MOUNT_POINT_NAME}",
    "sudo mount -o loop ${BUILD}/${DISK_IMAGE_NAME} ${BUILD}/${MOUNT_POINT_NAME}",
    "sudo mkdir -p ${BUILD}/${MOUNT_POINT_NAME}/EFI/BOOT",
    "sudo cp ${BUILD}/${BOOTLOADER_NAME}.efi ${BUILD}/${MOUNT_POINT_NAME}/EFI/BOOT/BOOTX64.EFI",
    "sudo cp ${BUILD}/${KERNEL_NAME}.elf ${BUILD}/${MOUNT_POINT_NAME}/${KERNEL_NAME}.elf",
    "sudo umount ${BUILD}/${MOUNT_POINT_NAME}",
]

#
# run qemu
#
[tasks.run_qemu]
description = "Run QEMU with the disk image and UEFI firmware"
command = "qemu-system-x86_64"
args = [
    "-enable-kvm",

    "-smp",
    "4",

    "-m",
    # "2G",
    "1G",

    "-bios",
    "${BUILD}/${OVMF_FILE_NAME}",

    "-drive",
    "format=raw,file=${BUILD}/${DISK_IMAGE_NAME}",

    # "--device",
    # "qemu-xhci,id=xhci",

    # "--device",
    # "usb-mouse",

    # "--device",
    # "usb-kbd",

    # "--device",
    # "usb-tablet",

    "--monitor",
    "stdio",

    # "-s",
    # "-S",
]

[tasks.pre_build]
script = ["rm -rf ${BUILD}", "mkdir ${BUILD}", "cp ${OVMF_FILE_NAME} ${BUILD}"]

[tasks.build_bootloader_debug]
description = "Build the bootloader and copy it to the build directory."
script = [
    "cd ${BOOTLOADER_NAME}",
    "cargo build --target x86_64-unknown-uefi",
    "cd ..",
    "cp ./${BOOTLOADER_NAME}/target/x86_64-unknown-uefi/debug/${BOOTLOADER_NAME}.efi ${BUILD}/${BOOTLOADER_NAME}.efi",
]

[tasks.build_kernel_debug]
description = "Build the kernel and copy it to the build directory."
script = [
    "cd ${KERNEL_NAME}",
    # "cargo build --target x86_64-unknown-none",
    "cargo build",
    "cd ..",
    "cp ./${KERNEL_NAME}/target/${KERNEL_BUILD_TARGET_NAME}/debug/${KERNEL_NAME}.elf ${BUILD}/${KERNEL_NAME}.elf",
]

[tasks.build_debug]
description = "Create a bootable image for debug."
dependencies = [
    "pre_build",
    "build_bootloader_debug",
    "build_kernel_debug",
    "make_image",
]

[tasks.run_debug]
dependencies = ["build_debug", "run_qemu"]
