version: '3.9'
services:
  pwn:
    image: pwnenv
    build:
      context: .
      dockerfile: runtime.dockerfile5a936267-6301-4cfc-bd00-7042b21a3aed
      args:
        - UUID=$(UUID_VAR)
    user: root
    network_mode: host
    tty: true
    privileged: true
    ulimits:
      core:
        soft: -1
        hard: -1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports:
      - 127.0.0.1:3333:3333
    volumes:
      - /home/sunset/projects/maizono_os:/root/workspace:rw
