[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror-no-std = "2.0.2"
common = { path = "../common" }
spin = "0.9.8"
arrayvec = { version = "0.7.6", default-features = false }
xhci = "0.9.2"
anyhow = { version = "1.0.89", default-features = false }
linked_list_allocator = "0.10.5"
uefi = "0.32.0"
