[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror-no-std = "2.0.2"
bootloader_api = "0.11.7"
once_cell = { version = "1.19.0", features = [
    "critical-section",
], default-features = false }
common = { path = "../common" }


[dependencies.noto-sans-mono-bitmap]
version = "0.3.0"
default-features = false
features = [
    "light",
    "size_16",
    "size_24",
    "unicode-basic-latin",
    "unicode-specials",
]
